# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np
a=np.random.random((3,3,3))
print(a)

[[[0.3627939  0.85014263 0.44907112]
  [0.28304074 0.22457976 0.77318088]
  [0.72844115 0.1874023  0.86594866]]

 [[0.57777586 0.61067158 0.0473787 ]
  [0.47441699 0.04322747 0.07560202]
  [0.07586743 0.47823855 0.41543816]]

 [[0.08131409 0.77818759 0.96857012]
  [0.31549582 0.57079002 0.44088885]
  [0.49686897 0.28766021 0.60946697]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
K = np.zeros ((8,8), dtype=int)
K[1::2, ::2]= 1
K[::2, 1::2] = 1
print (K)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.97448244 0.30258413 0.30234836 0.65340658 0.08689595]
 [0.81092002 0.92296292 0.12771073 0.95451111 0.54356682]
 [0.83505897 0.66308607 0.77238904 0.19201337 0.80657614]
 [0.22323021 0.99502612 1.         0.12817141 0.56847702]
 [0.         0.56024503 0.16705179 0.85143748 0.31994735]]


# 5.  How to find common values between two arrays?

In [30]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [31]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [8]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[8.65883943e-01 2.22609512e-01 3.85276678e-01 4.04307535e-01
 5.02609642e-01 7.53273726e-01 1.73294350e-01 1.03935828e-01
 0.00000000e+00 5.39557581e-04]


# 9. How to print all the values of an array?

In [10]:
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [11]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[ 0.07252647, -0.19429411,  0.24304082,  0.13718684, -0.0533762 ,
        -0.03135782, -0.13846679,  0.06647556, -0.12263718,  0.02090241],
       [ 0.24254363, -0.39240895, -0.06900026, -0.3159427 ,  0.53919604,
        -0.27513597,  0.11826613,  0.46322842,  0.03033674, -0.34108309],
       [ 0.5428933 , -0.39899179,  0.12978313, -0.11676714, -0.32405162,
         0.03285098,  0.40942403, -0.44206856, -0.04217532,  0.20910298],
       [-0.26624268, -0.11650049, -0.19411185,  0.28997014,  0.28383098,
        -0.39438323,  0.0958336 ,  0.1773533 ,  0.01593738,  0.10831285],
       [ 0.30171359, -0.03528153,  0.03345744, -0.35466389, -0.28982916,
        -0.00930899,  0.18725946,  0.41168568,  0.13010594, -0.37513854]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [22]:
Z = np.ones(8)
print(Z)
I = np.random.randint(0,len(Z),10)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1.]
[0 7 3 3 6 5 5 0 6 1]
[3. 2. 1. 3. 1. 3. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [16]:
A = np.random.randint(0,10,(3,3))
print(A)
B= np.random.randint(0,10,(3,3))
print(B)
np.diag(np.dot(A, B))


[[0 5 5]
 [4 1 0]
 [3 5 9]]
[[2 8 6]
 [3 1 5]
 [7 1 2]]


array([50, 33, 61])

# 13.How to find the most frequent value in an array?

In [13]:
Z = np.random.randint(0,10,50)
print (Z)
a=np.bincount(Z)
print(a)
b=np.bincount(Z).argmax()
print(b)
print('rank:', np.bincount(Z).argmax())

[4 8 6 7 1 9 6 7 6 9 1 8 1 3 3 7 6 5 8 9 5 6 5 8 1 5 3 3 0 5 4 3 4 0 1 6 0
 5 5 4 7 6 5 1 3 0 4 7 1 6]
[4 7 0 6 5 8 8 5 4 3]
5
rank: 5


# 14.How to get the n largest values of an array

In [29]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 8
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9997 9994 9996 9995 9998 9993 9992]


# 15.How to create a record array from a regular array?

In [19]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
